### ISSUE TITLE
how should  I use the websocket protocal to return a value from the server ?

### ISSUE THREAD

**Issue by xiaoliuliu2050** [5HT/n2o#176]
client code:   
I use the Bert and html5 websocket to send a request   as follows:

ws = new bullet("ws://ecs999.eicp.net:8023/ws/hui2hui_register");
             ws.onopen = function() {
                 window.alert("onopen111sss1!");
                 //ws.send("xx");
                 ws.send(Bert.encode(Bert.tuple(Bert.atom('client'),
                 Bert.tuple(Bert.atom('phone_auth'),"+380.."))));
             };
            ws.onmessage = function(event) {
                window.alert(event.data);              
            };

server code:  hui2hui_register.erl  

I use the event handler to handle it as follows ,

-module(hui2hui_register).
-compile(export_all).
-include_lib("n2o/include/wf.hrl").

main() ->cowboy_req:reply(200, "<<xxx>>").

event({client,{phone_auth,Phone}}) ->
 % io:format("Phone: ˜p˜n",[Phone]),
  wf:info(?MODULE, "Web Socket Pid: ˜p",[self()]).

as a result , onmessage event triggered ,I just get a alert box  with "[]" content in it ,
and not the result "Web Socket Pid:"  ,
I want to  know where  I am wrong?
please

**Comment by 5HT** [comment]
Wrong:
```erlang
main() ->cowboy_req:reply(200, "<>").
```
you should return HTML page with all N2O JavaScript files.
then you in your JavaScript you should use [bert.js](https://github.com/5HT/n2o/blob/master/priv/protocols/bert.js) which doesn't have Bert.encode but
```javascript
enc(tuple(atom('client'),tuple(atom('phone_auth'),"+380..")))
```
