### ISSUE TITLE
undefined function mad_repl:main/1 when building sample

### ISSUE THREAD

**Issue by 23min** [5HT/n2o#178]
Following the readme kickstart section:

Repl Params: []
escript: exception error: undefined function mad_repl:main/1
  in function  lists:foreach/2 (lists.erl, line 1323)
  in call from escript:run/2 (escript.erl, line 747)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1 
  in call from init:start_em/1 

environment OS X 10.9.5
GNU bash, version 4.3.11(1)-release (x86_64-apple-darwin12.5.0)
Erlang 17.4

**Comment by 5HT** [comment]
n2o sample depens on 
```
   {mad,    ".*", {git, "git://github.com/synrc/mad",          {tag, "master"} }},
```
mad master,
mad_repl in mad's master doesn't have main/1, it has main/2
https://github.com/synrc/mad/blob/master/src/mad_repl.erl#L51

**Comment by 23min** [comment]
I know it doesn't have main/1, but I followed the readme exactly to the letter and that was the result.

$ git clone git://github.com/5HT/n2o
$ cd n2o/samples
$ ./mad deps compile plan repl

**Comment by 5HT** [comment]
fixed
