### ISSUE TITLE
http://localhost:8000/ no connection

### ISSUE THREAD

**Issue by kklepper** [5HT/n2o#193]
$ git clone git://github.com/5HT/n2o 
$ cd n2o/samples 
$ ./mad deps compile plan repl

netstat shows that port 8000 is not served. Maybe I should tell you that Yaws is running as a service on port 8081.

The last output looks like this:

----------------
Compiling /vagrant/Erlang/n2o/samples/n2o/samples/apps/review/src/config.erl
Writing /vagrant/Erlang/n2o/samples/n2o/samples/apps/review/ebin/review.app
DTL Compiling /vagrant/Erlang/n2o/samples/n2o/samples/apps/review/priv/templates/message.html
:0: Warning: function render_tag/3 is unused
DTL Compiling /vagrant/Erlang/n2o/samples/n2o/samples/apps/review/priv/templates/login.html
:0: Warning: function render_tag/3 is unused
DTL Compiling /vagrant/Erlang/n2o/samples/n2o/samples/apps/review/priv/templates/index.html
:0: Warning: function render_tag/3 is unused
Plan Params: []
Ordered: [crypto,compiler,syntax_tools,mnesia,kernel,stdlib,kvs,fs,cowlib,
          ranch,gproc,erlydtl,cowboy,n2o,review,active,kjell,mad,rest,sh]
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [async-threads:10] [kernel-poll:false]

Configuration: [{n2o,[{port,8000},
                      {app,review},
                      {route,routes},
                      {log_modules,config},
                      {log_level,config},
                      {event,pickle}]},
                {kvs,[{dba,store_mnesia},
                      {schema,[kvs_user,kvs_acl,kvs_feed,kvs_subscription]}]}]
Applications: [crypto,compiler,syntax_tools,mnesia,kernel,stdlib,kvs,fs,
               cowlib,ranch,gproc,erlydtl,cowboy,n2o,review,active,kjell,
               mad,rest,sh]
Kjell v.0.2.3
1> Setting up watches.  Beware: since -r was given, this may take a while!
                                                                          Watches established.

1> 

----------------

This looks like I am in Erlang shell, and this is true.

Before you ask:

vagrant@vagrant-ubuntu-trusty-64:/vagrant/Erlang$ sudo apt-get install inotify-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
inotify-tools is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Win7 64 bit, Vagrant box Ubuntu Trusty

**Comment by 5HT** [comment]
Let me guess, ESL version of Erlang? :-)

**Comment by 5HT** [comment]
I will add to README that the only version of supported Erlang is builded with kerl or from sources.

**Comment by kklepper** [comment]
1> Setting up watches.  Beware: since -r was given, this may take a while!
                                                                          Watches established.

1> application:start(review).
{error,{already_started,review}}
2>

**Comment by 5HT** [comment]
mnesia is started?

**Comment by kklepper** [comment]
> mnesia is started?

I'm sorry, I'm a newbie and would have to do my research to be able to answer your question. Simultaneously, I tried to set up ChicagoBoss, and experienced the same problem. So I guess the reason is pretty simple: we are in VirtualBox and have to account for port forwarding. Let's see if I can figure this out.

**Comment by kklepper** [comment]
I found it:

  config.vm.network "forwarded_port", guest: 8000, host: 7000
  config.vm.network "forwarded_port", guest: 8001, host: 7001

But I have to suspend my test right now, I must take a break for some time. I'll come back to you.

**Comment by kklepper** [comment]
Ok, that was it. But what about this:

    [...]
    /vagrant/Erlang/n2o/samples/apps/review/src/index.erl:36: Warning: variable 'User' is unused
    Compiling /vagrant/Erlang/n2o/samples/apps/review/src/config.erl
    Writing /vagrant/Erlang/n2o/samples/apps/review/ebin/review.app
    DTL Compiling /vagrant/Erlang/n2o/samples/apps/review/priv/templates/message.html
    escript: exception error: undefined function erlydtl:compile/3
      in function  lists:foreach/2 (lists.erl, line 1336)
      in call from mad_compile:dep/4 (src/mad_compile.erl, line 49)
      in call from mad_compile:deps/4 (src/mad_compile.erl, line 11)
      in call from lists:foreach/2 (lists.erl, line 1336)
      in call from escript:run/2 (escript.erl, line 752)
      in call from escript:start/1 (escript.erl, line 276)
      in call from init:start_it/1

**Comment by 5HT** [comment]
please clean all (by removing) and update everything.

**Comment by kklepper** [comment]
Wow! Great! Thank you very much!

By the way, kerl did not succeed:

    checking for tgetent in -ltinfo... no
    checking for tgetent in -lncurses... no
    checking for tgetent in -lcurses... no
    checking for tgetent in -ltermcap... no
    checking for tgetent in -ltermlib... no
    configure: error: No curses library functions found
    configure: error: /bin/bash '/home/vagrant/.kerl/builds/17.4/otp_src_17.4/erts/configure' failed for erts

But now I don't have to dig into that anymore, I guess.

**Comment by 5HT** [comment]
:-)
