### ISSUE TITLE
Using xhrPolling  way to connect server , i can not take the request body out?

### ISSUE THREAD

**Issue by xiaoliuliu2050** [5HT/n2o#195]
```javascript
the client side ,here is the code:
            ws= new bullet("http://ecs999.eicp.net:8000/ws/hui2hui_index");
            ws.onopen = function() {
                window.alert("open!");
               
                var str="{'client',[{'rpc_api_id','hui2hui_Create_User'}]}";
                ws.send(str);
            };
```

I debug the server code and find that it go in the handle method  in the file named "bullet_handle.erl" ：  
----------------
handle(Req, State=#state{handler=Handler, handler_state=HandlerState},
		<<"POST">>) ->
--------------

and in this method , here is the code and my dubug info 

	case cowboy_req:body(Req) of
		{ok, Data, Req2} ->

    % -- Debug info ----------------------------------------------
      io:format("bullet_handler:handle3(): data: ~s~n", [Data]),
    % -- Debug info ----------------------------------------------

			case Handler:stream(Data, Req2, HandlerState) of
				{ok, Req3, HandlerState2} ->
					{ok, Req3, State#state{handler_state=HandlerState2}};
				{reply, Reply, Req3, HandlerState2} ->
					{ok, Req4} = cowboy_req:reply(200, [], Reply, Req3),
					{ok, Req4, State#state{handler_state=HandlerState2}}
			end;
		{error, _} ->
			%% An error occurred, stop there.
			{ok, Req, State}
	end.

however no matter what i send from the client side ,i just can not take the request body out ?

so i am here  hope to get help.

**Comment by 5HT** [comment]
:-) you are doing it completely wrong. N2O uses websocket and BERT encoding. It has nothing to do with JSON and XHR requests.

ws.send(enc(tuple(atom('client'),tuple(atom('rpc_api_id'),"hui2hui_Create_User"))));

Also be sure that your 'rpc_api_id' atom is present on Erlang VM (somewhere in code).

**Comment by xiaoliuliu2050** [comment]
the n2o contains a file named bullet.js,
in this file ,it defines two ways of transports,
one is websocket ,and other one is xhrpooling ,
you said  n2o use websocket to connect to server ,
then  what does the xhrpolling used for ?


here is the code : 


// N2O Bullet

function bullet(url) {

    var CONNECTING = 0;
    var OPEN = 1;
    var CLOSING = 2;
    var CLOSED = 3;

    var transports = {

        websocket: function() {
            var transport = null;
           // if (window.WebSocket) { transport = window.WebSocket; }
            //if (transport) { return {'heart': true, 'transport': transport}; }
            return null;
        },

        xhrPolling: function() {
            var timeout;
            var xhr;

            nextPoll();

            var fake = {
                readyState: CONNECTING,

                receive: function(data) {
                    window.alert(data);
                    if (fake.readyState == CONNECTING) { fake.readyState = OPEN; fake.onopen(fake); }
                    if (data.length != 0) { fake.onmessage({'data': data }); }
                    if (fake.readyState == OPEN) {
                        nextPoll();
                    }
                },

                send: function(data) {
                    if (this.readyState != CONNECTING && this.readyState != OPEN) return false;
                    window.alert(data);
                    var fakeurl = url.replace('ws:', 'http:').replace('wss:', 'https:');
                    window.alert(fakeurl);
                    var request = new XMLHttpRequest();
                    request.open('POST',fakeurl,true);
                    request.setRequestHeader('Content-Type',
                        'application/x-www-form-urlencoded; charset=utf-8');
                    request.setRequestHeader('X-Socket-Transport','xhrPolling');
                    request.onload = function() { fake.receive(request.response); };
                    request.send(data);
                    window.alert("1");
                    return true;
                },
                close: function(){
                    this.readyState = CLOSED;
                    xhr.abort();
                    clearTimeout(timeout);
                    fake.onclose();
                },
                onopen: function(){},
                onmessage: function(){},
                onerror: function(){},
                onclose: function(){}
            };

            function poll(pooling){
                window.alert("poll");
                var fakeurl = url.replace('ws:', 'http:').replace('wss:', 'https:');
                var request = new XMLHttpRequest();
                request.open('GET',fakeurl,true);
                request.setRequestHeader('Content-Type',
                    'application/x-www-form-urlencoded; charset=utf-8');
                request.setRequestHeader('X-Socket-Transport','xhrPolling');
                request.onload = function() { fake.receive(request.response); };
                request.onerror = function() { fake.onerror(); };
                request.send();
                window.alert(fakeurl);
            }

            function nextPoll() { timeout = setTimeout(function(){poll();}, 1000); }


            return {'heart': false, 'transport': function(){ return fake; fake.nextPoll(); }};
        }
    };

    var tn = 0;
    function next() {
        var c = 0;

        for (var f in transports) {
            if (tn == c) {
                var t = transports[f]();
                if (t) { var ret = new t.transport(url); ret.heart = t.heart; return ret; }
                tn++;
            }
            c++;
        }
        return false;
    }

    var stream = new function() {
        var isClosed = true;
        var readyState = CLOSED;
        var heartbeat;
        var delay = 80;
        var delayDefault = 80;
        var delayMax = 10000;

        var transport;
        function init() {

            isClosed = false;
            readyState = CONNECTING;
            transport = next();

            if (!transport) {
                delay = delayDefault;
                tn = 0;
                stream.ondisconnect();
                setTimeout(function(){init();}, delayMax);
                return false;
            }

            transport.onopen = function() {
                delay = delayDefault;

                if (transport.heart) { 
                    heartbeat = setInterval(function(){stream.onheartbeat();}, 4000);
                }

                if (readyState != OPEN) { readyState = OPEN; stream.onopen(); }
            };

            transport.onclose = function() {
                if (isClosed) { return; }

                transport = null;
                clearInterval(heartbeat);

                if (readyState == CLOSING){
                    readyState = CLOSED;
                    stream.onclose();
                } else {
                    if (readyState == CONNECTING) tn++;
                    delay *= 2;
                    if (delay > delayMax) { delay = delayMax; }
                    isClosed = true;
                    setTimeout(function() { init(); }, delay);
                }
            };
            transport.onerror = transport.onclose;
            transport.onmessage = function(e){
            stream.onmessage(e);
            };
        }

        init();

        this.onopen = function(){};     this.oninit = function(){};
        this.onmessage = function(){};  this.ondisconnect = function(){ initialized = false; };
        this.onclose = function(){};    this.onheartbeat = function(){
            return this.send('PING'); };

        this.setURL = function(newURL) { url = newURL; };
        this.send = function(data){
            if (transport) return transport.send(data); else return false;
        };
        this.close = function(){
            readyState = CLOSING;
            if (transport) transport.close();
        };
    };

    return stream;
}

**Comment by 5HT** [comment]
You don't need to copy N2O code to Issue tracker. I know N2O pretty well and even If I didn't I would find it in my codebase. XHR is fallback mechanism for browser who doesn't support WebSockets.

**Comment by 5HT** [comment]
See #196
