### ISSUE TITLE
cowboy_http_handler(bullet_handler.erl) can not get http post body(cowboy_req:body(Req))

### ISSUE THREAD

**Issue by whw987** [5HT/n2o#196]
hi, Mr Namdak Tonpa,

I found a bug when I use cowboy_http_handler(bullet_handler.erl) can not get http post `body(cowboy_req:body(Req))`

```erlang
code(bullet_handler.erl):
handle(Req, State=#state{handler=Handler, handler_state=HandlerState},
		<<"POST">>) ->
%% ------- Debug info ----------------------------------------------
  io:format("bullet_handler.handle_post_step_1: Data: ~w~n", [ cowboy_req:body(Req) ]),
% ------------------------------------------------------------
	case cowboy_req:body(Req) of
		{ok, Data, Req2} ->

%% ------- Debug info ----------------------------------------------
  io:format("bullet_handler.handle_post: Data: ~w~n", [ cowboy_req:body(Req2) ]),
% ------------------------------------------------------------
			case Handler:stream(Data, Req2, HandlerState) of
				{ok, Req3, HandlerState2} ->
					{ok, Req3, State#state{handler_state=HandlerState2}};
				{reply, Reply, Req3, HandlerState2} ->
					{ok, Req4} = cowboy_req:reply(200, [], Reply, Req3),
					{ok, Req4, State#state{handler_state=HandlerState2}}
			end;
		{error, _} ->
			%% An error occurred, stop there.
			{ok, Req, State}
	end.
```

In my debug code line, I cannot get the data in the http request body when I send a valid http post request from the client side with the XHR pooling(websocket is OK).

But I take some effort, I find the bug is the following line in your n2o_websocket.erl

    Req1 = wf:header(<<"Access-Control-Allow-Origin">>, Origin, NewCtx#cx.req),

after this line is executed, the http post body is disappeared, so cause I cannot get http post data in 
`case cowboy_req:body(Req) of` in bullet_handler.erl

So, I think following line maybe have a bug,

```erlang
    Req1 = wf:header(<<"Access-Control-Allow-Origin">>, Origin, NewCtx#cx.req),
```

I look forward to fix this problem. I'm using N2O in our recent project .

Thank you in advance.

**Comment by 5HT** [comment]
Why you think Bullet handler is for HTTP requests?
for HTTP request we have n2o_document endpoint and rest endpoint,
bullet handler is underlying handler of n2o_websocket endpoint and in no case is for HTTP POST requests.

**Comment by whw987** [comment]
Our App background:
Our mobile App build based on cordova/phonegap, UI build based on ionic, and no need nitrogen to  generate gendynamic web page as our App UI. Our App data channel to the server is mainly based on N2O websocket, but if android OS version is lower than 4.4, the N2O websocket can not work, so the XHR pooling is the good solution we can adopt, in this case our app data channel to the server can be build with http post based on XHR pooling, it can work. And I find your bullet_handler.erl has a branch to handle the http post request, so I adopt it.
If you have better solution, please give me a recommendation.
Thank you very much.

**Comment by 5HT** [comment]
No mater you you XHR polling or WebSockets you should use 

```erlang
ws.send(enc(tuple(atom('client'),"Message"))).
```

You should also be aware that XHR fallback will work in stateless mode due to limitations in underlying cowboy library `bullet`.

**Comment by whw987** [comment]
Thank you for replying. 

I know cowboy library bullet.js and n2o.js can automatically process websocket and XHR fallback, and have the same ws object. this design is very good. now in fact I have used ws.send(enc(tuple(atom('client'),"Message")));  to send request to the server.

The data channel between App and server is mainly build on N2O websocket, I try to add another XHR fallback is only a compatible for android OS version older than 4.4, the XHR fallback is my second selection,  N2O websocket is the first, and now it works well.

In the server side, my code is depend on bullet_handler.erl, it has XHR fallback and websocket branch, it process the App side RPC (ws.send(enc(tuple(atom('client'),"Message")))) request and dispatch the request to my Erlang process for a variety of  business logic, after the Erlang business logic code is complete, it also return the result to bullet_handler.erl, then bullet_handler.erl reply the return results to the App side. This is my core design of our project.

Now, the websocket branch worked very well. unfortunately XHR fallback can not work, last week I debug into your code(of course I first of all let window.WebSocket = null), find after this code(in n2o_websocket.erl) executed, the XHR request body data become blank, the XHR fallback branch failed.
 Req1 = wf:header(<<"Access-Control-Allow-Origin">>, Origin, NewCtx#cx.req),

So I think if you can help me resolve this problem, my code will also work successfully on XHR fallback branch.
I expect you give me a help.  ^_^

**Comment by 5HT** [comment]
Is that mean that in you are experienced functionality downgrade after upgrading N2O master branch?
Which version was ok for you and which version become broken?

**Comment by whw987** [comment]
Sorry, where or which file to set {n2o,[{origin,<<"*">>}]} ?

**Comment by 5HT** [comment]
In sys.config

**Comment by whw987** [comment]
I have just test the code several times under your guide, this problem still occurred.

Now my test N2O code is your latest main branch, last week I also test with your new release 2.1, the problem is the same.

the following is my config and the test code.

sys.config
[
 {n2o, [{port,8000},{app,review},{route,routes},{log_modules,config},{log_level,config},{origin,<<"*">>},{event,pickle}]},
 {kvs, [{dba,store_mnesia}, {schema, [kvs_user, kvs_acl, kvs_feed, kvs_subscription ]} ]}
].


n2o_websocket.erl

...
init(Req) ->
    wf:actions([]),

%% ------- Debug info ----------------------------------------------
  io:format("n2o_websocket.init: Data0: ~w~n", [ cowboy_req:body(Req) ]),
% ------------------------------------------------------------

    Ctx = wf_context:init_context(Req),
    NewCtx = wf_context:fold(init,Ctx#cx.handlers,Ctx),
    wf:context(NewCtx),
    wf:reg(broadcast,{wf:peer(Req)}),

%% ------- Debug info ----------------------------------------------
io:format("n2o_websocket.init: Data1: ~w~n", [ cowboy_req:body(Req) ]),
% ------------------------------------------------------------

    {Origin, _} = cowboy_req:header(<<"origin">>, Req, <<"*">>),

%% ------- Debug info ----------------------------------------------
io:format("n2o_websocket.init: Data2: ~w~n", [ cowboy_req:body(Req) ]),
% ------------------------------------------------------------

%%    Req1 = wf:header(<<"Access-Control-Allow-Origin">>, Origin, NewCtx#cx.req),

ConfigOrigin = wf:to_binary(wf:config(n2o,origin,Origin)),
wf:info(?MODULE,"Origin: ~p",[ConfigOrigin]),
Req1 = wf:header(<<"Access-Control-Allow-Origin">>, ConfigOrigin, NewCtx#cx.req),

%% ------- Debug info ----------------------------------------------
io:format("n2o_websocket.init: Data3: ~w~n", [ cowboy_req:body(Req1) ]),
% ------------------------------------------------------------

    {ok, Req1, NewCtx}.

...

I test by printing out the cowboy_req:body(Req), when I send a request like ws.send(enc(tuple(atom('client'),"Message"))); from the client side.

only n2o_websocket.init: Data0, n2o_websocket.init: Data1, n2o_websocket.init: Data2  can output the cowboy_req:body(Req) data,  but  n2o_websocket.init: Data3 is empty(<<>>).

**Comment by 5HT** [comment]
Despite I fixed XHR for now I cannot guarantee that XHR will be supported in future.
