### ISSUE TITLE
mad bundle doesn't work

### ISSUE THREAD

**Issue by rgrinberg** [5HT/n2o#197]
Not quite sure if this is a mad bug or a problem with the sample. Steps to reproduce:

```
$ cd samples
$ mad deps compile bundle
$ ./samples
```

Will now error with `undefined function samples:main/1`.

P.S. I couldn't make bundle work in my little [sample app](https://github.com/rgrinberg/n2omegle) as well after following what you said in irc, e.g. adding a main function to n2omegle.

**Comment by 5HT** [comment]
You misusing bundle command. You should do

```
$ mad bundle web_app 
```

And specify the as a parameter the module which has main/1 exported function.

**Comment by rgrinberg** [comment]
OK, thanks that works for samples. So out of curiosity, how does it expect to work when you don't provide the argument to `mad bundle`. It still generates the executable after all.

**Comment by 5HT** [comment]
As a default mad imply the name of top directory of the project.

**Comment by rgrinberg** [comment]
OK, Thanks.
