### ISSUE TITLE
Question about N2O application server start and run to background as service. 

### ISSUE THREAD

**Issue by whw987** [5HT/n2o#208]
Hi, Mr Namdak Tonpa,

We have made a application server based on the N2O, and we must run the server in background as service. We have a question to ask you.
 what method is the best to run the N2O development server as  background service?
now, we perform it like this:
# nohup ./mad deps compile plan repl &
but a error appeared, the info:
=ERROR REPORT==== 24-Apr-2015::19:05:15 ===
Error in process <0.163.0> with exit value: {badarg,[{erlang,register,[user,<0.164.0>],[]},{user,start_port,1,[{file,"user.erl"},{line,53}]}]}

if run to like this: # ./mad deps compile plan repl, no any error message to appear.

We waiting your good suggestion.

Thank you advance.

**Comment by 5HT** [comment]
Thank you for the question.

For running synrc application as a service you need to use `otp.mk` makefile script that runs mad applications with `run_erl` and `to_erl` OTP app helpers for VM instantiating and console attaching. Please see sample in https://github.com/synrc/otp.mk/blob/master/otp.mk 

Befor run ensure that `.applist` is created.

**Comment by whw987** [comment]
Thank you very much.

**Comment by 5HT** [comment]
If this helps you may close the issue.

**Comment by whw987** [comment]
Thank you, now I made my app server as a service in ground under your guide , except for make stop fail. I close this issue.

**Comment by 5HT** [comment]
'otp.mk' is skeleton, you have to take your own responsibility to proper configuring `Makefile`.
`make stop` is working at least in `n2o/sample`.

**Comment by whw987** [comment]
my Linux is centos 6.6, make start works OK,  but make stop, maybe my Makefile configuration is not correct. but make stop is not the main problem, I can resolve it later, so I close this issue.
