### ISSUE TITLE
problem of user sessions, wf:user(User)  and wf:user()

### ISSUE THREAD

**Issue by yandrey** [5HT/n2o#209]
Our login page became broken after n2o update (we used pretty old n2o). In previous version we use wf:user(User) to set corresponding session variable after successful login and wf:user() to get it. Before, it was enough to have user sessions. But now after wf:user(User) all sessions have same user via wf:user(). 
Could this be a bug or wf:user(User), wf:user() are not enough to set/get user-session variable now?

**Comment by 5HT** [comment]
Th breaking changes is n2o_session manager two modes: auto cookies, or manual cookies:
https://github.com/5HT/n2o/blob/master/src/handlers/n2o_session.erl#L9-L11

In manual mode you should call `n2o_session:ensure_sid/3` like `n2o_session:ensure_sid([],?CTX,[])` in event(init). Now in N2O we do this automatically by default. If you want to fallback to manual mode you should put in `sys.config` following n2o option `{auto_session,disabled}`.

However `n2o/sample` is working normally with that changes. The thing you have something broken after this changes means misusing of `n2o_session`. Please take a look onto official `n2o/sample` with working `wf:user` API.

**Comment by yandrey** [comment]
yes n2o_session:ensure_sid([],?CTX,[]) in event(init) works for us. 

many thanks

**Comment by 5HT** [comment]
Could you leave feedback on N2O usage? Company, Person and Project Name ?

**Comment by yandrey** [comment]
I'll do that when we go live.
Best regards
